### PR TITLE
Add support for Ubuntu Noble

### PR DESCRIPTION
**Pull request by ruffsl**
- https://github.com/balena-io-library/base-images/issues/1082
- https://github.com/balena-io/contracts/pull/432

### CODE REVIEW

**Comment by dadaroce** [comment]
@ruffsl as you test it on a device?

**Comment by ruffsl** [comment]
@dadaroce , not yet. We've been waiting on Balena to learn how this kind of the upstreaming process works here.
cc @nghiant2710 @klutchell ?

**Comment by klutchell** [comment]
@ruffsl was there a particular architecture or device type you were waiting for? I can do a manual run of some images before the [next scheduled run on the first of next month](https://github.com/balena-io-library/base-images/blob/f98a9baeac2de226d7c7620428c8a7cb520d1f6d/.github/workflows/all-bake.yml#L10-L13).

**Comment by ruffsl** [comment]
> was there a particular architecture or device type you were waiting for?

@klutchell , we were waiting for the intel nuc verent so we could start validating the migration of our fleet:

> balena-base-images/device-base/intel-nuc/ubuntu/noble

**Comment by klutchell** [comment]
I've started a manual run here: https://github.com/balena-io-library/base-images/actions/runs/10458309340

**Pull request closed without merging**
