### PR TITLE
CI: Update checkout settings

### PR DESCRIPTION
**Pull request by Page-**
Change-type: patch

### CODE REVIEW

**Comment by klutchell** [comment]
I was going to get to this today, thanks for doing it @Page- !

**Review by klutchell — CHANGES_REQUESTED** [review]
@Page- these changes need to be made to the [workflow templates](https://github.com/balena-io-library/base-images/tree/master/scripts/blueprints/workflows), or they will get overwritten next time the workflows are generated.

**Comment by Page-** [comment]
@klutchell this PR already updates those blueprints doesn't it?

**Comment by klutchell** [comment]
So it does, apologies, they were buried at the end of the 106 changed files.

For future reference the PR workflow will build the workflow files and you don't need to change them manually.

**Review by klutchell — APPROVED** [review]

**Pull request merged**
